name: DnD Compass CI Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Arduino Lint
        uses: arduino/arduino-lint-action@v2 # Use the latest version
        with:
          # Optional inputs:
          compliance: specification # 'permissive', 'specification', or 'strict'
          library-manager: update   # Use 'submit' or 'update' for Library Manager checks
          project-type: sketch    # 'sketch', 'library', or 'platform'

      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:avr:nano # Example FQBN for an Arduino Uno
          sketch-paths: |
            - ./
          libraries: |
            - name: Servo
            - name: ArduinoUniqueID
            #- name: SoftwareSerial
